### ISSUE TITLE
pushState

### ISSUE THREAD

**Issue by bobo183** [sdc-fe/Framework7-Website#1]
设置了pushState ＝ true, 浏览器的url是变化了，但是，点击浏览器后退按钮，页面不发生变化了！
使用了requirejs，但没用别的类库！

**Comment by lihongxun945** [comment]
@bobo183  不要提到这里，这个只是网站的仓库。提到 这里去：https://github.com/sdc-fe/Framework7-Plus/issues/9
而且这个bug已经提过了。
